### ISSUE TITLE
Support to 1.21.3 ?

### ISSUE THREAD

**Issue by Kox598xd** [flowerinsnow-lights-opensource/HideArmour#11]
Is it possible to make the mod also compatible with version 1.21.3 on Neoforge ?

**Comment by flowerinsnowdh** [comment]
Thank you, I think I can do that.

I used to think no one used it anymore.

**Comment by flowerinsnowdh** [comment]
Done.

https://github.com/flowerinsnow-lights-opensource/HideArmour/releases/tag/v8.0.0-beta.1%2Bneoforge
